name: Builder
on:
  schedule:
    - cron: "0 0 */7 * *"
  workflow_dispatch:
jobs:
  AUR_Kernel:
    strategy:
      matrix:
        build: [linux-xanmod-tt-uksm-cjktty, linux-xanmod-tt-uksm-cjktty-headers]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build packages for arch
        uses: actions/checkout@v3.0.2
      - name : update submodule
        run: git submodule update --recursive --remote
      - id: makepkg
        uses: JPratama7/pkgbuild-action@aur-gcc
        with:
          namcapDisable: true
          pkgdir: ${{ matrix.build }}
          makepkgArgs: "--skippgpcheck"
      - name: Upload Artifact
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: "latest"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
